### ISSUE TITLE
Link to local SwaggerUI is incorrect

### ISSUE THREAD

**Issue by j8-redis** [redis-field-engineering/redis-connect-dist#11]
Swagger UI
The [Redis Connect Swagger UI](
https://redis-field-engineering.github.io/redis-connect-api-docs => https://redis-field-engineering.github.io/redis-connect-api-docs
) is available on port 8282 by default.

If you're running locally, you can point your browser to
[http://localhost:8282/swagger-ui/index.html => https://github.com/redis-field-engineering/redis-connect-dist/blob/main](https://github.com/redis-field-engineering/redis-connect/issues/144)

As you can see the second href points to github and not to the local swagger

**Comment by viragtripathi** [comment]
Updated the localhost url to show as text instead of hyperlink.
