### ISSUE TITLE
Composite Target key Update is failing on stream transaction

### ISSUE THREAD

**Issue by nmsundar-coder** [redis-field-engineering/redis-connect-dist#13]
When connecting oracle with redis connect. Table have composite primary key, so targetKey was true for multiple fields in a table. 

During stream transaction, update is throwing an error stating keyset cannot be serialized to String.

**Comment by viragtripathi** [comment]
@nmsundar-coder Can you share your Job configuration/payload file and Oracle table definition so I can take a look?

**Comment by nmsundar-coder** [comment]
@viragtripathi  

Please find the requested details attached. Below is the error received 

`09:19:32.095 [Thread-8] ERROR redis-connect - Instance: JobId: {connect}:job:cdc-job Key: DEBEZIUM_PROPERTY:12:AmalJose Operation: U will handle an exception within one of its stages at Checkpoint: {"commit_scn":"20135287:1:08000c00c6050000","connect:timestamp":"1702275572087","src:tx:seq":"1","connect:name":"connect:cp:cdc-job","src:tx:time":"1702275570000","snapshot_scn":"20133021","scn":"20135286"} - RootException: [java.lang.ClassCastException: class java.util.HashMap$KeySet cannot be cast to class java.lang.String (java.util.HashMap$KeySet and java.lang.String are in module java.base of loader 'bootstrap'),       at io.lettuce.core.codec.StringCodec.encodeKey(StringCodec.java:36),    at io.lettuce.core.protocol.CommandArgs$KeyArgument.encode(CommandArgs.java:689),   at io.lettuce.core.protocol.CommandArgs.encode(CommandArgs.java:362),   at io.lettuce.core.protocol.Command.encode(Command.java:126),       at io.lettuce.core.protocol.AsyncCommand.encode(AsyncCommand.java:185),         at io.lettuce.core.protocol.CommandEncoder.encode(CommandEncoder.java:93),  [wrapped] io.netty.handler.codec.EncoderException: Cannot encode command. Please close the connection as the connection state may be out of sync.,  at io.lettuce.core.protocol.CommandEncoder.encode(CommandEncoder.java:96),      at io.lettuce.core.protocol.CommandEncoder.encode(CommandEncoder.java:78),  at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107),        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881),         at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863),      at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968),    at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856),        at io.lettuce.core.protocol.CommandHandler.writeSingleCommand(CommandHandler.java:421),     at io.lettuce.core.protocol.CommandHandler.write(CommandHandler.java:387),  at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879),         at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:940),      at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1247),   at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174), at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167),   at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470),      at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569),        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997),    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74),       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30),       at java.base/java.lang.Thread.run(Thread.java:1583)]`

[cdc-job.json](https://github.com/redis-field-engineering/redis-connect-dist/files/13631723/cdc-job.json)
[tableDef.txt](https://github.com/redis-field-engineering/redis-connect-dist/files/13631725/tableDef.txt)

**Comment by viragtripathi** [comment]
@nmsundar-coder you can also email us at virag@redis.com and kyle.banker@redis.com if you have any more questions or want to setup a call to go over your use-case. Who are you working with at Redis?

**Comment by nmsundar-coder** [comment]
Hi @viragtripathi  

Can you try updating PROPERTY_KEY column instead of status column ? I am facing error while updating one of the target key when using multiple target key ?

**Comment by viragtripathi** [comment]
@nmsundar-coder I updated the PROPERTY_KEY column and it worked as expected. I tried with ID column as well. Can you send an email so we can setup a call to see your setup?

**Comment by nmsundar-coder** [comment]
@viragtripathi  

It is working as expected ! Issue was with table creation in oracle . 

Constraint  PRIMARY KEY ("ID") was missing PROPERTY_KEY column. So target_key : true column should be a composite primary key in table as well ?

**Comment by viragtripathi** [comment]
@nmsundar-coder glad it's working as expected. Thanks for the confirmation.
