### ISSUE TITLE
JobOwner key not updated on Start RedisCDC for MSSQL

### ISSUE THREAD

**Issue by brahmesh98** [redis-field-engineering/redis-connect-dist#4]

**Comment by viragtripathi** [comment]
@brahmesh98 Do you use Redis Enterprise?

**Comment by brahmesh98** [comment]
@viragtripathi I am using the docker Redis Enterprise. Everything same as in documenation (https://github.com/RedisLabs-Field-Engineering/redis-connect-dist/blob/master/connectors/mssql/demo/README.md).
