### ISSUE TITLE
Oracle connector

### ISSUE THREAD

**Issue by ik2478** [redis-field-engineering/redis-connect-dist#6]
l'm interested in the redis connector for oracle but don't see any read.me doc or setup instructions.Will it be available soon?

**Comment by viragtripathi** [comment]
Hi @ik2478 Redis Connect Oracle connector is currently in incubation. You should see demo steps / setup instructions in a  couple of weeks. What version of Oracle do you use and are you an existing Redis Enterprise customer?

**Comment by ik2478** [comment]
19C and not a Redis Enterprise customer.

**Comment by viragtripathi** [comment]
19c is not supported yet and this is only available for Redis Enterprise customers but you are welcome to try it out once we have the steps published.
