### ISSUE TITLE
Windows version can't create a job due to credentialsFilePath

### ISSUE THREAD

**Issue by ronan-vargas** [redis-field-engineering/redis-connect-dist#9]
Hello,
I successfully started Redis Connect in my Windows Machine, but when I try to create a job for Oracle integration through API, it throws an error: 

"ERROR: Failed to save configuration for JobName: cdc_job Validation Failure: Invalid CredentialsFilePath: C:\credentialscdc".
<img width="570" alt="print_api_error_create_job" src="https://user-images.githubusercontent.com/19451745/180822060-51a61588-be04-47cc-83fb-1dcff83e2677.png">

- The equivalent curl command is listed below:

```curl -X POST "http://localhost:8282/connect/api/v1/job/config/cdc_job" -H "accept: */*" -H "Content-Type: multipart/form-data" -F "file=@cdc_job.json;type=application/json"```

- The credential file exists in credentials path:

<img width="671" alt="print_c_credentials_cdc" src="https://user-images.githubusercontent.com/19451745/180821423-f5dd6826-f44d-4c9e-927e-8f5fff56dd10.png">

- "File" parameter has a JSON file like this:
<img width="573" alt="print_log_cdc_json" src="https://user-images.githubusercontent.com/19451745/180821002-ed64d4f7-8bba-4abd-9878-55a8d1690490.png">

**Comment by viragtripathi** [comment]
Hi @ronan-vargas, I don't see your Redis (target) credentials file (or maybe it's not visible in the screenshot you have provided). Can you please try this,

Move all credentials file from the location you have chosen for credentialsFilePath except these,
- redisconnect_credentials_jobmanager.properties (this is used for the metadata DB connection to store all of Redis Connect metadata)
- redisconnect_credentials_redis_cdc-job.properties (this is used for the target Redis DB connection)
- redisconnect_credentials_oracle_cdc-job.properties (this is used for the source i.e. Oracle connection)

The file format for Redis Connect credentials are as follows,
redisconnect_credentials_<source|target>_<jobName>.properties, the source name is same as database product name on the jdbc url and target is always redis. I noticed you have one file with UPPERCASE ORACLE and that shouldn't be there either.

redisconnect_credentials_jobmanager.properties, there will always be one jobmanager file per Redis Connect instance/node.

The fact that you're able to start Redis Connect instance means you had no issue connecting to your metadata Redis DB and the credentialsPath for this must be correct in the jobmanager.properties file which is read at the Instance startup to connect to Redis so all of Redis Connect metadata can be persisted in Redis. Also, your Redis Enterprise DB endpoint doesn't seem correct so please fix the Redis URI and provide a valid Redis Enterprise DB endpoint.

**Comment by ronan-vargas** [comment]
Hello @viragtripathi, thank you very much for answering me. 

After reviewing some steps (before your answer) I've successfully created a job through Redis Connect. For to do that, I also needed to put "ojdbc*.jar" in the "lib" directory and also used "cdc-job" as jobName, instead of "cdc_job".
However, now Redis Connect throws an exception when I try to start the job for the first time, using 'load' as jobType.

```2022-07-26 10:42:32,773 ERROR redis-connect-manager [JobManagerThreadpool-2] Instance: 22996@IBM-PF3R4N79 failed to initialize JobId: {connect}:task:partition:2:cdc-job:C##RCUSER.EMP EXCEPTION MESSAGE: RedisConnectValidationException:  STACKTRACE: [Validation Failure: InstanceId: 22996@IBM-PF3R4N79 will not start JobId: {connect}:task:partition:2:cdc-job:C##RCUSER.EMP because there are no records in Table: C##RCUSER.EMP, 	at com.redis.connect.pipeline.producer.impl.load.RDBInitialLoadProducer.startSourceConnection(RDBInitialLoadProducer.java:78), 	at com.redis.connect.cluster.service.JobManager.startJobProducer(JobManager.java:713), 	at com.redis.connect.cluster.service.JobClaimer.initializeJob(JobClaimer.java:214), 	at com.redis.connect.cluster.service.JobClaimer.claimJob(JobClaimer.java:171), 	at com.redis.connect.cluster.service.JobClaimer.run(JobClaimer.java:81), 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539), 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305), 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305), 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136), 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635), 	at java.base/java.lang.Thread.run(Thread.java:833)]```

The problem is that my C##RCUSER.EMP table has records and these records was inserted before starting the job.

select count(*) from C##RCUSER.emp;

count(*)
---------
11

My configuration files and Connect logs are in attachment:

[cdc-job.json.txt](https://github.com/redis-field-engineering/redis-connect-dist/files/9190482/cdc-job.json.txt)
[redisconnect_credentials_jobmanager.properties.txt](https://github.com/redis-field-engineering/redis-connect-dist/files/9190483/redisconnect_credentials_jobmanager.properties.txt)
[redisconnect_credentials_oracle_cdc-job.properties.txt](https://github.com/redis-field-engineering/redis-connect-dist/files/9190484/redisconnect_credentials_oracle_cdc-job.properties.txt)
[redisconnect_credentials_redis_cdc-job.properties.txt](https://github.com/redis-field-engineering/redis-connect-dist/files/9190485/redisconnect_credentials_redis_cdc-job.properties.txt)
[redis-connect-22996.log.txt](https://github.com/redis-field-engineering/redis-connect-dist/files/9190486/redis-connect-22996.log.txt)
[redis-connect-manager-22996.log.txt](https://github.com/redis-field-engineering/redis-connect-dist/files/9190488/redis-connect-manager-22996.log.txt)

**Comment by viragtripathi** [comment]
Thanks @ronan-vargas you already made good progress. You're right for Oracle, you do need the client driver jar as we can't include it due to licensing. I see you have some issue with the driver you're using. From the connector log, `No suitable driver STACKTRACE: [java.sql.SQLException: No suitable driver` 

Can you try this [Oracle JDBC Driver](https://download.oracle.com/otn-pub/otn_software/jdbc/1915-OAuth2/ojdbc8.jar) and restart your instance then re-run the oracle-job? Also, please change the partition to 1 if you only have 11 records to load otherwise you would fail in another validation as <500 records can only have 1 partition OR if you want to add more records then see here, https://github.com/redis-field-engineering/redis-connect-dist/tree/main/examples/oracle/demo#initial-loader-steps

**Comment by ronan-vargas** [comment]
Hello,
Considering initial loader steps link, I've used a distinct Oracle docker image, and this one doesn't have "sqlldr" tool. Consequently, I've inserted records on "emp" table directly by Oracle SQL Developer.
Moreover, I've noticed that "load_sql.sh" script references a table called "employees". However, I think that previous script only creates "emp" table.

About your last answer, even changing "partitions" property in .json configuration file, the error "there are no records in Table: C##RCUSER.EMP" is still occurring.

Couldn't be the "#" in user name (C##RCUSER) a problem? My point is that "#" character is commonly used for comments in Properties files.

**Comment by viragtripathi** [comment]
Please see, https://github.com/redis-field-engineering/redis-connect-dist/blob/main/examples/oracle/demo/load_sql.sh#L26 for the load if you still need it.

The error was due to the driver you're using earlier. Have you replaced the driver with the link I sent?

**Comment by viragtripathi** [comment]
The username with "#" is fine and won't cause any issue. 

Also, since you're using PDB's you may run into this issue with 19c, https://github.com/oracle/docker-images/issues/1663 and if you get `Got minus one from a read call` error then add this to your rediconnect.cmd and jdbc url then restart your instance

set REDISCONNECT_JAVA_OPTIONS=-XX:+HeapDumpOnOutOfMemoryError -Xms1g -Xmx2g **-Doracle.net.disableOob=true**

"databaseURL": "jdbc:oracle:thin:@localhost:1522/ORCLPDB1**?oracle.net.disableOob=true**",

**Comment by ronan-vargas** [comment]
The driver that I was using is also called "ojdbc8.jar", but the file in my machine was a bit larger (4963 KiB vs. 4369 KiB).
I've replaced the file with the one you suggested, restarted Redis Connect, updated the job again and tried to start.
Unfortunately, the exception "there are no records in Table..." is still occurring.
Now I'll try this new configuration (I'm using Oracle 12c) for *JAVA_OPTIONS and I'll send a message in case of any problem.

Thanks in advance.

**Comment by viragtripathi** [comment]
If you're using 12c then you shouldn't see `Got minus one from a read call` error I mentioned earlier. Are you still seeing any driver related error in the connector log i.e. `redis-connect-<PID>.log`?

**Comment by viragtripathi** [comment]
Hi @ronan-vargas as discussed on the call, I am going to close this issue as all of your setup issue has been resolved and you have both load and stream job running with Oracle as a source and Redis Enterprise DB as target.

**Comment by ronan-vargas** [comment]
Hi @viragtripathi , OK, but the only thing that isn`t so clear to me is the fact that the setup works in "Initial Load" scenario (even with the Oracle's service name with ".localdomain" suffix) but it doesn't work in "CDC" scenario.
I'll send by email the contact of everyone that was in the meeting.

**Comment by viragtripathi** [comment]
Hi @ronan-vargas, it probably works with initial load as it's a different connection using the databaseURL in the payload but stream job i.e. cdc uses a different connection that is started and managed by Debezium based on the `database.` properties and when you pass `database.dbname` with `.localadmin` suffix, you see the oracle driver error with TNS listener issue.
